import whisper
from transformers import BertTokenizer
import torch

# Load once
whisper_model = whisper.load_model("base")   #base is a smaller version of the Whisper model, which is designed to be faster and more efficient while still providing good transcription quality for many use cases. The "base" model is a good choice for applications that require a balance between performance and accuracy, especially when running on limited hardware resources. By loading the model once at the module level, we can reuse it across multiple calls to the transcribe_segment function without incurring the overhead of loading the model each time.
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")  #bert-base-uncased is a widely used pre-trained model that has been trained on a large corpus of English text. It is designed to be case-insensitive, meaning it treats uppercase and lowercase letters as the same. This makes it a good choice for many natural language processing tasks, including tokenization for text input in our multimodal analysis pipeline. By loading the tokenizer once at the module level, we can reuse it across multiple calls to the transcribe_segment function without incurring the overhead of loading the tokenizer each time.

def transcribe_segment(audio_path):
    """
    Convert audio -> text 
    """

    result = whisper_model.transcribe(audio_path)   #.transcribe() is a high-level function that handles the entire transcription process, including loading the audio, processing it through the model, and returning the transcription results in a structured format. The result is a dictionary that contains various pieces of information about the transcription, including the transcribed text, timestamps, and confidence scores. By calling result["text"], we extract just the transcribed text from the result dictionary, which is what we are interested in for our use case.
    return result["text"]

def encode_text(text, max_length = 64):    #max_length is a parameter that specifies the maximum length of the tokenized sequence. If the input text exceeds this length, it will be truncated to fit within the specified limit. This is important for ensuring that the input to the model does not exceed its maximum input size, which can lead to errors or inefficient processing. By setting a reasonable max_length, we can balance between capturing enough context from the text and maintaining efficient processing for our multimodal analysis pipeline.
    """
    Convert text -> token ids + attention mask
    """
    encoding = tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=max_length,
        return_tensors="pt"    #return_tensors="pt" tells the tokenizer to return the tokenized output as PyTorch tensors. This is important for our use case because we will be feeding these tokenized inputs directly into a PyTorch model for further processing. By specifying return_tensors="pt", we ensure that the output is in the correct format for our model, allowing us to seamlessly integrate the text encoding step into our multimodal analysis pipeline without needing additional conversions.
    )
    
    input_ids = encoding["input_ids"]   # input_ids is the tensor containing the token IDs generated by the tokenizer. Each token in the input text is mapped to a unique integer ID based on the tokenizer's vocabulary. This tensor will be used as input to the model for processing the text data in our multimodal analysis pipeline.
    attention_mask = encoding["attention_mask"]  # attention_mask is a tensor that indicates which tokens in the input sequence are actual text and which are padding. It contains 1s for valid tokens and 0s for padding tokens. This mask helps the model to focus on the relevant parts of the input text while ignoring the padding, which is crucial for efficient processing and accurate predictions in our multimodal analysis pipeline.

    return input_ids, attention_mask